### ISSUE TITLE
Can't authenticate throught CAS UK

### ISSUE THREAD

**Issue by PObdr** [ReCodEx/web-app#159] opened 2017-12-31 13:44 UTC
I can't log in throught CAS even when using right credentials. the server response is 

> Server response: The ticket 'ST-1822-jjxOeioY1zPR1C4zlqsK-cas.cuni.cz' cannot be validated as the response from the server is corrupted or incomplete.

This is a big problem for me, I have to do some homeworks...

**Comment by Neloop** [comment] 2017-12-31 14:01
Hello,
interestingly we do not deployed new version in a while, maybe some problems with CAS service? I will investigate further and get back with more info in no time.

**Comment by LadaKa** [comment] 2017-12-31 14:21
I have the same problem.

**Comment by PObdr** [comment] 2017-12-31 14:22
I can log into another apps (like ckis.cuni.cz) with no problem.

**Comment by Neloop** [comment] 2017-12-31 15:20
Status update: CAS seems to completely ignore communication in JSON format and serves us XML to which we obviously are not prepared. Stand by for quickfix it might take a while considering date and time.

**Comment by SemaiCZE** [comment] 2017-12-31 16:46
The issue is that CAS suddenly dropped its version to 3.5.2 (which is 4 years old) and does not support features we rely on. Hotfix is not possible (requires more changes that we are now capable of) so you have to wait. My personal opinion is that CAS is running from old backup and will be fixed soon, but who knows. If the problem is not fixed tomorrow afternoon, we will try to communicate with CAS admins and hopefully fix this.

**Comment by Neloop** [comment] 2018-01-01 16:30
CAS seems to be back to 4.2 version. Authentication is working again...

**Closed by Neloop** 2018-01-01 16:30 UTC
